import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/session-provider";
import Nav from "@/components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SST Fundementals",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <main className="mx-auto max-w-5xl text-2xl flex gap-2 text-white">
            <Nav />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
